### PR TITLE
sudo: Fix (re)setting HOME with sudo backend

### LINKED ISSUE #117: We should not strip HOME and TERM
ok, there is a problem with HOME, if not stripped, it point to the SUDO_USER - so the right way will be to evaluate it from `/etc/passwd`.

See https://github.com/lxqt/pcmanfm-qt/issues/961 for a detailed discussion of the issue.

LXQt: Current git

### PR DESCRIPTION
**Pull request by palinek**
With the -E (--preserve-env) parameter and our stripped environment sudo
does not set HOME. With explicitly defining the list of preserved env
vars (--preserve-env=FOO,BAH..) sudo sets the HOME correctly in the
priviledged process.

Note: This needs at least sudo v1.8.21
(https://www.sudo.ws/repos/sudo/rev/a6bc511a2e81).

fixes #117

### CODE REVIEW

**Comment by agaida** [comment]
Tested - and perfect for me.

**Comment by palinek** [comment]
... and is it OK to relay on features of sudo up from v1.8.21 ?

**Comment by agaida** [comment]
i have no problem with - no one will port back LXQt to things like the current debian stable - so any newer distribution will be fine. And for LTS things - if one want to port back LXQt to Ubuntu 16.04 (LTS) -- not our problem, sudo will be the easiest of the problem. Such things contradict the meaning of Long Term Supported.

**Comment by agaida** [comment]
unblocked for debian buster

**Pull request merged**
