### PR TITLE
sudo: Prevent malicious attempts for command injection

### PR DESCRIPTION
**Pull request by palinek**
With the #46 we created a possibility for injection of commands via the LC_ALL env. variable (I didn't think of such malicious usage at that time).
Example of such malicious script is as easy as (**do not try it w/o the `echo`**):
`LC_ALL=\'\ 'echo rm -f /'\' ./lxqt-sudo ls`
... command to execute presented to the user will be `ls`, but...

We prevent this by simply checking if the LC_ALL contains `'` ...

### CODE REVIEW

**Comment by agaida** [comment]
GTM

**Comment by agaida** [comment]
Why not?

**Comment by setharnold** [comment]
The usual chars to worry about with shell injection attacks includes:

```
`$(){}<>|:;&%'"~*!
```

and likely others I can't recall. So I'm curious why only one char was selected here.

Thanks

**Comment by agaida** [comment]
@palinek - your turn

**Comment by palinek** [comment]
Because we are assembling the assignment for LC_ALL [here](https://github.com/lxqt/lxqt-sudo/blob/master/sudo.cpp#L243) as `LC_ALL='` + `the previous value` + `'` ... so `the previous value` can be anything except it is trying to end the quoting by `'`.

@setharnold please, if you see some kind of attack, that can be used, report/demonstrate it. And we will try our best to fix any vulnerability.

**Pull request merged**
