### PR TITLE
Fixed the layout and line-break

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxqt/lxqt/issues/1505

### CODE REVIEW

**Comment by palinek** [comment]
It still doesn't scale well...with default font size 19, I'm getting this:
screenshot

**Comment by tsujan** [comment]
You probably increased font size after showing the dialog.

**Comment by palinek** [comment]
> You probably increased font size after showing the dialog.

Nope.

**Comment by palinek** [comment]
> Can't reproduce it here:

IMO this screenshot can't be made from lxqt-sudo built from current master (+ this PR), because the command (and parameters) would be quoted with apostophes.

**Comment by tsujan** [comment]
echo

**Comment by palinek** [comment]
Strange... something in my/your system must make a difference :)

**Comment by tsujan** [comment]
> Strange... something in my/your system must make a difference :)

It shouldn't be the style -- I'd checked with Fusion and Breeze too. Font?

**Comment by tsujan** [comment]
For the sake of certainty (even KWin doesn't tolerate this font size):

absurd

**Comment by agaida** [comment]
Only a question - can we make the dialog a bit bigger at all - there is no need to keep it that small

**Comment by tsujan** [comment]
@agaida We can do various things with the dialog: make it it bigger (not needed, IMO -- we can add spacers), make it non-resizable, add a small spacer above `Attempt #1`, add an empty line above `Please enter...`, etc. Here, my plan wasn't making it more elegant.

**Comment by agaida** [comment]
ok - in this case GTM

**Pull request merged**
